### ISSUE TITLE
Random Programming Line Below the comment area

### ISSUE THREAD

**Issue by Robinn4K** [aemi-dev/aemi#14]
**Describe the bug**

**To Reproduce**
1. Go to 'any post site'
2. Scroll down to 'comment area'
3. See error

**Expected behavior**
below the coment you can see a huge programming line "document.getElementById("comment").setAttribute( "id", "a4b02d71d3f261af96fcd0e99f26dcfd" );document.getElementById("cd13b2f645").setAttribute( "id", "comment" );"

**Screenshots**
![Screenshot 2021-04-23 002618](https://user-images.githubusercontent.com/8049170/115792436-97c62a80-a3ca-11eb-812f-5e15e2f3ec3e.png)

 - OS: [tried on Windows, iOS, Android]
 - Browser [all]
 - Version [all]

**Additional context**
document.getElementById("comment").setAttribute( "id", "a4b02d71d3f261af96fcd0e99f26dcfd" );document.getElementById("cd13b2f645").setAttribute( "id", "comment" );

**Comment by Robinn4K** [comment]
I have found the error, i used Antispam Bee Plugin. And this created this coding line.

**Comment by aemi-dev** [comment]
Hi @Robinn4K ,

This issue has been fixed in [Aemi v2.0.9](https://github.com/aemi-dev/aemi/releases/tag/2.0.9).
What version of Aemi are you using ?

Also, this issue is a duplicated of "[JavaScript under Comments](https://github.com/aemi-dev/aemi/issues/8)" and the workaround is described there.

Best Regards
