### ISSUE TITLE
Bug: Post Listing Column Layout Single/Two Column

### ISSUE THREAD

**Issue by danieljungdong** [aemi-dev/aemi#23]
**Describe the bug**
Post Listing Column Layout is published as "single column" while post listing is still showing as two columns

**To Reproduce**

1. Go to Wordpress-> Theme -> customize
2. Click on the Post page / set Aemi->Content Loop->Post Listing Column Layout-> SingleColumn && Sticky Post Layout in Listing-> One Column
3. Clear caching, go to the live page in production and click on the post page. See two column content loop / cards.
4. See error: id="site-loop" class="site-loop span-1 no-img  default-width two-columns"

**Expected behavior**
Expected to see div with class="one-columns"
<img width="1334" alt="Screen Shot 2021-12-30 at 12 35 11 AM" src="https://user-images.githubusercontent.com/2926076/147736924-135f46fb-5cb1-44fe-9522-4a95f55361e2.png">
<img width="1410" alt="Screen Shot 2021-12-30 at 12 34 23 AM" src="https://user-images.githubusercontent.com/2926076/147736926-14151b5b-650b-4d94-9df8-c262a9106b58.png">

**Screenshots**

**Environment Description:**

- Aemi Version: Version: 2.0.12
- WordPress Version: Version 5.8.2
- Related Plugins and their versions

**Additional context**

**Comment by danieljungdong** [comment]
Not sure how it was solved. I changed the setting to two columns, hit publish, and then changed it back to one column and then hit public. Probably conflicted with some other plugins i'm using?

Thanks for the this template though-- really enjoy the style and the ease of use.

**Comment by g-cqd** [comment]
Hi @danieljungdong 

I honestly acknowledge this behaviour. It's weird and I couldn't fully understand it myself. My idea here is that there's a problem with how the parameter is stored/cached (which is quite weird because I only use default features of WordPress for that). So, the rationale is that when you encounter a problem like this, you need to "flush" the parameter by changing it and saving the edit then getting back to the wanted setting.

I'm really sorry for the inconvenience. I hope it will be fixed in the next major update I'll release. It may be in 2022 but I don't know yet when (you can find the current work in the aemi 2.1.0 branch). My timetable is quite busy.

By the way, I would love to really thaaaaank you for your sponsoring. You're the first, you'll never be forgotten. Thank you again.

Best Regards, best wishes for the next year 🙏
Guillaume
