### ISSUE TITLE
Disqus Comments

### ISSUE THREAD

**Issue by DakotaDAllen** [aemi-dev/aemi#5]
Not sure if this is a bug or a removed feature, but I cannot seem to get Disqus commenting to work with Aemi 2.0.6. Are there certain steps I need to take to enable this? Any help is appreciated!

**Comment by aemi-dev** [comment]
Hi @DakotaDAllen ,

Disqus commenting is not a native feature of Aemi Theme and I admit I do not really know if Aemi Theme supports it. How would you add Disqus Commenting to the theme ? If it is via a plugin, which plugin ?

Best Regards
Guillaume

**Comment by DakotaDAllen** [comment]
Thank you for your response. [This is the plugin here](https://wordpress.org/plugins/disqus-comment-system/). After disabling it, I noticed that I cannot see the native comment system either with the new Aemi theme. I have disabled many of my other plugins in case they were conflicting, however, I still cannot get it working.

**Comment by aemi-dev** [comment]
Okay, I'll take a look at that.
Hope it won't be too long.

Regards,

**Comment by aemi-dev** [comment]
Your issue was caused by a bug in my code. When I published the first release of Aemi 2, WordPress theme check asked me to remove some of the new features and I remove too mush of my code notably comments hooks.

Aemi 2.0.7 should fix your issue.
If you like Aemi, please feel free to leave a comment on [Aemi WordPress Repository page](https://wordpress.org/themes/aemi/) or to star this repo.

Best Regards,
Guillaume
