### ISSUE TITLE
JavaScript under Comments

### ISSUE THREAD

**Issue by davidlohner** [aemi-dev/aemi#8]
Hi,

I just published my redesigned wordpress site with aemi. I really like this theme, great work! 
But: I got some strange JavaScript under the comment-section on each post (see https://postimg.cc/N9rZjwWX). 
Maybe you can have a look at this and help me get rid of it?

See https://davidlohner.de and choose any blog post.

Best,
David

**Comment by aemi-dev** [comment]
Hi @davidlohner ,

To fix it, add this tiny custom CSS to WordPress :
```
script {
    display: none !important;
}
```
Due to an error of me, Aemi display every element whatever in some block including script tag. It will be fixed in a future update.

However, I'm glad you're using Aemi and you're liking it. At the time, I'm too busy to work on it but be sure, problems and bugs will be fixed.

Thanks for reaching me !
Best Regards,
Guillaume

**Comment by davidlohner** [comment]
Thanks for the quick reply. This fix worked!

**Comment by aemi-dev** [comment]
Hi again @davidlohner,

This issue is officially fixed. Please fill free to keep me up to date if anything goes wrong.

Best Regards,

Guillaume
